# Generated by Django 4.2.20 on 2025-07-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('request_accepted', 'Request Accepted'), ('follow_request', 'Follow Request')], max_length=20),
        ),
    ]
