# Generated by Django 4.2.20 on 2025-06-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
